version: 2.1

executors:
  python-ssh-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  deploy:
    executor: python-ssh-executor
    steps:
      - checkout
      - run:
          name: Install SSH client
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client
      - run:
          name: Setup SSH Key from Environment Variable
          command: |
            echo "$SSH_PRIVATE_KEY" > ~/temp_ssh_key
            chmod 600 ~/temp_ssh_key
      - run:
          name: Deploy Python Chatbot Facebook
          command: |
            echo "=== Starting deployment ==="
            ssh -i ~/temp_ssh_key -o StrictHostKeyChecking=no $USER_NAME@103.161.97.193 \
              "bash ~/devops/deploy_python_chatbot_facebook.sh"
            echo "=== Deployment finished ==="

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy